#Cav Commands to find maxtem
cav_commands_SRY_first = """
cav cavIMC MC2 nMC2in MC2 nMC2refl
cav cavPRX PRMHR nPRMHRb ITMXHR nITMXs2
cav cavPRY PRMHR nPRMHRb ITMYHR nITMYs2
cav cavSRY SRMHR nSRMHRa ITMYHR nITMYs2
cav cavSRX SRMHR nSRMHRa ITMXHR nITMXs2
cav cavXARM ITMXHR nITMX2 ETMXHR nETMX1
cav cavYARM ITMYHR nITMY2 ETMYHR nETMY1
cav cavFC IMFC nIMFC3 IMFC nIMFC4
cav cavOMC OMC_HROC nOMC_HROC_refl OMC_HROC nOMC_HROC_in
"""

cav_commands_SRX_first = """
cav cavIMC MC2 nMC2in MC2 nMC2refl
cav cavPRX PRMHR nPRMHRb ITMXHR nITMXs2
cav cavPRY PRMHR nPRMHRb ITMYHR nITMYs2
cav cavSRX SRMHR nSRMHRa ITMXHR nITMXs2
cav cavSRY SRMHR nSRMHRa ITMYHR nITMYs2
cav cavXARM ITMXHR nITMX2 ETMXHR nETMX1
cav cavYARM ITMYHR nITMY2 ETMYHR nETMY1
cav cavFC IMFC nIMFC3 IMFC nIMFC4
cav cavOMC OMC_HROC nOMC_HROC_refl OMC_HROC nOMC_HROC_in
"""

cav_commands_FC_first = """
cav cavFC IMFC nIMFC3 IMFC nIMFC4
cav cavIMC MC2 nMC2in MC2 nMC2refl
cav cavPRX PRMHR nPRMHRb ITMXHR nITMXs2
cav cavPRY PRMHR nPRMHRb ITMYHR nITMYs2
cav cavSRX SRMHR nSRMHRa ITMXHR nITMXs2
cav cavSRY SRMHR nSRMHRa ITMYHR nITMYs2
cav cavXARM ITMXHR nITMX2 ETMXHR nETMX1
cav cavYARM ITMYHR nITMY2 ETMYHR nETMY1
cav cavOMC OMC_HROC nOMC_HROC_refl OMC_HROC nOMC_HROC_in
"""

cav_commands_FC_last = """
cav cavIMC MC2 nMC2in MC2 nMC2refl
cav cavPRX PRMHR nPRMHRb ITMXHR nITMXs2
cav cavPRY PRMHR nPRMHRb ITMYHR nITMYs2
cav cavSRX SRMHR nSRMHRa ITMXHR nITMXs2
cav cavSRY SRMHR nSRMHRa ITMYHR nITMYs2
cav cavXARM ITMXHR nITMX2 ETMXHR nETMX1
cav cavYARM ITMYHR nITMY2 ETMYHR nETMY1
cav cavOMC OMC_HROC nOMC_HROC_refl OMC_HROC nOMC_HROC_in
cav cavFC IMFC nIMFC3 IMFC nIMFC4
"""

