% Runs GWINC with some nominal parameters

f_LOLO = 5;
f_HIHI = 5000;

ifo = IFOModel;

[sss,nnn] = gwinc(f_LOLO,f_HIHI,ifo,SourceModel,3);


%% Make Pretty Plot
fontname = 'Helvetica';
fsize1 = 32;
hXLabel = xlabel('Frequency [Hz]', 'FontName', fontname, ...
                                    'FontSize', fsize1   );
hYLabel = ylabel('Strain [1/\surdHz]', 'FontName', fontname, ...
                                       'FontSize', fsize1   );
axis([8 5000 3e-25 1e-21]);
grid off
grid on
grid minor
title(' ')

hLeg = legend(' Quantum fluctuations',...
         ' Seismic vibrations',...
         ' Newtonian Gravity',...
         ' Suspension Thermal noise',...
         ' Mirror Coating Brownian',...
         ' Mirror Coating Thermo-Optic',...
         ' Mirror Substrate Brownian',...
         ' Residual Gas',...
         ' Total noise',...
         'Location','NorthEast');
set( gca, 'FontName', fontname, 'FontSize', fsize1 );
% set([hXLabel, hYLabel], ...
%     'FontName'   , 'Times',...
%     'FontSize'   , 34         );
set(hLeg             , ...
     'FontSize'   , 16           );
%set( hTitle                    , ...
%    'FontSize'   , 12          , ...
%    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'on'     , ...
  'TickDir'     , 'in'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , 0.1*[1 1 1], ...
  'YColor'      , 0.1*[1 1 1], ...
  'XTick'       , logspace(-4, 4, 9), ...
  'YTick'       , logspace(-25,-11,15), ...
  'FontSize'    , 28 ,...
  'LineWidth', 1.5);

hlines = get(gca,'Children');
set(hlines(:),'LineWidth',4);
set(hlines(1),'LineWidth',7,'Color',0.33*[1 1 1]);

%% pretty plot
orient landscape
set(gcf,'Position',[900 400 1000 700])
set(gcf,'PaperPositionMode','auto')
%saveas(gcf, 'aLIGO_gwinc', 'fig')
%print -depsc -r600 aLIGO_gwinc.eps
%[a,b] = system('epstopdf aLIGO_gwinc.eps --nocompress --autorotate=All')


